#!/usr/bin/env python3
"""
build.py — generate docs/ static site from courses/*/course/units markdown.
Run from repo root: .venv\\Scripts\\python.exe build.py
"""

import os, re, json, shutil
import markdown as md_lib

COURSES_DIR = "courses"
DOCS_DIR    = "docs"
MD_EXTS = ["fenced_code", "tables", "nl2br", "sane_lists", "attr_list"]

# ---------------------------------------------------------------------------

def to_html(text):
    return md_lib.markdown(text, extensions=MD_EXTS)

def read(path):
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8-sig") as f:
        return f.read()

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def extract_title(md_text, fallback=""):
    m = re.search(r"^#\s+(.+)", md_text, re.MULTILINE)
    return m.group(1).strip() if m else fallback

def slug_title(folder_name):
    parts = folder_name.split("-", 1)
    if len(parts) < 2:
        return folder_name
    return parts[1].replace("-", " ").capitalize()

def uid_from_folder(folder_name):
    return folder_name.split("-")[0]

# ---------------------------------------------------------------------------

def for_single_page(md_text):
    """Rewrite assignment.md / rubric.md pointers to in-page anchors."""
    if not md_text:
        return md_text
    md_text = re.sub(r"\[([^\]]*)\]\((?:\./)?assignment\.md\)", r"[\1](#assignment)", md_text, flags=re.IGNORECASE)
    md_text = re.sub(r"\[([^\]]*)\]\((?:\./)?rubric\.md\)", r"[\1](#rubric)", md_text, flags=re.IGNORECASE)
    md_text = re.sub(r"\[assignment\.md\]\(#assignment\)", r"[Assignment](#assignment)", md_text, flags=re.IGNORECASE)
    md_text = re.sub(r"\[rubric\.md\]\(#rubric\)", r"[Rubric](#rubric)", md_text, flags=re.IGNORECASE)
    md_text = re.sub(r"(^## Assignment\s*\n+)See \[Assignment\]\(#assignment\)\.?\s*$",
                     r"\1The assignment is included on this page — [jump to Assignment](#assignment).", md_text, flags=re.MULTILINE)
    md_text = re.sub(r"(^## How you will be assessed\s*\n+)See \[Rubric\]\(#rubric\)\.?\s*$",
                     r"\1How you are scored is included on this page — [jump to Rubric](#rubric).", md_text, flags=re.MULTILINE)
    return md_text

# ---------------------------------------------------------------------------

def load_course(course_dir):
    meta = json.loads(read(os.path.join(course_dir, "meta.json")))
    units_dir = os.path.join(course_dir, "course", "units")
    units = []
    if os.path.isdir(units_dir):
        for folder in sorted(os.listdir(units_dir)):
            path = os.path.join(units_dir, folder)
            if not (os.path.isdir(path) and re.match(r"U\d+", folder)):
                continue
            uid = uid_from_folder(folder)
            readme = read(os.path.join(path, "README.md"))
            title = extract_title(readme, slug_title(folder))
            title = re.sub(r"^U\d+\s*[—–-]+\s*", "", title).strip()
            units.append({
                "uid": uid, "folder": folder, "title": title,
                "readme": readme,
                "assignment": read(os.path.join(path, "assignment.md")),
                "rubric": read(os.path.join(path, "rubric.md")),
                "phase": meta["unitPhase"].get(uid, 0),
            })
    return meta, units

# ---------------------------------------------------------------------------

HEADER = """<header class="site-header">
  <a class="logo" href="{home}">training</a>
  <nav>
    <a href="{home}">Courses</a>
  </nav>
</header>"""

FOOTER = """<footer class="site-footer">
  Static training materials — generated by build.py
</footer>"""

def shell(title, css, body, home="index.html"):
    header = HEADER.format(home=home)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <link rel="stylesheet" href="{css}">
</head>
<body>
{header}
{body}
{FOOTER}
</body>
</html>"""

PHASE_CLASSES = ["ph0","ph1","ph2","ph3","ph4","ph5","ph6","ph7","ph8"]

def phase_class(meta, phase_num):
    return PHASE_CLASSES[int(phase_num)] if int(phase_num) < len(PHASE_CLASSES) else "ph0"

# --- root index: course catalog ---

def build_root(courses):
    cards = []
    for c in courses:
        cards.append(f'''<a class="unit-card" href="{c["slug"]}/index.html">
  <div class="utitle">{c["title"]}</div>
  <div class="phase-title">{c["tagline"]}</div>
</a>''')
    body = f"""<main class="page">
  <div class="hero">
    <h1>Training courses</h1>
    <p>Self-paced, human-assessed courses with static materials. Pick a course to begin.</p>
  </div>
  <div class="unit-grid">
    {"".join(cards)}
  </div>
</main>"""
    return shell("Training courses", "style.css", body, home="index.html")

# --- course index ---

def build_course_index(meta, units):
    by_phase = {}
    for u in units:
        by_phase.setdefault(u["phase"], []).append(u)
    sections = []
    for phase_num in sorted(by_phase):
        ph_label = meta["phases"].get(str(phase_num), str(phase_num))
        cards = []
        for u in by_phase[phase_num]:
            cards.append(f'''<a class="unit-card" href="units/{u["folder"]}/index.html">
  <div class="uid">{u["uid"]}</div>
  <div class="utitle">{u["title"]}</div>
</a>''')
        sections.append(f"""<div class="phase-block">
  <span class="phase-label {phase_class(meta, phase_num)}">Phase {phase_num}</span>
  <div class="phase-title">{ph_label}</div>
  <div class="unit-grid">
    {"".join(cards)}
  </div>
</div>""")
    empty = '<p><em>Units are being authored. Check back soon.</em></p>' if not units else ""
    body = f"""<main class="page">
  <a class="back-link" href="../index.html">All courses</a>
  <div class="hero">
    <h1>{meta["title"]}</h1>
    <p>{meta["hero"]}</p>
  </div>
  {"".join(sections)}
  {empty}
</main>"""
    return shell(meta["title"], "../style.css", body, home="../index.html")

# --- unit page ---

def build_unit(meta, unit, prev_unit, next_unit):
    uid, title = unit["uid"], unit["title"]
    ph_num = unit["phase"]
    ph_label = f'Phase {ph_num} — {meta["phases"].get(str(ph_num), "")}'

    readme_html = to_html(for_single_page(unit["readme"]))
    assignment_html = to_html(for_single_page(unit["assignment"])) if unit["assignment"] else "<p><em>No assignment file found.</em></p>"
    rubric_html = to_html(for_single_page(unit["rubric"])) if unit["rubric"] else "<p><em>No rubric file found.</em></p>"

    prev_link = f'<a class="prev" href="../{prev_unit["folder"]}/index.html">{prev_unit["uid"]} {prev_unit["title"]}</a>' if prev_unit else ""
    next_link = f'<a class="next" href="../{next_unit["folder"]}/index.html">{next_unit["uid"]} {next_unit["title"]}</a>' if next_unit else ""

    body = f"""<main class="page">
  <a class="back-link" href="../../index.html">{meta["title"]} — all units</a>

  <div class="unit-header">
    <div class="uid-badge">{uid}</div>
    <h1>{title}</h1>
    <span class="phase-badge {phase_class(meta, ph_num)}">{ph_label}</span>
  </div>

  <nav class="section-nav">
    <a href="#lesson">Lesson</a>
    <a href="#assignment">Assignment</a>
    <a href="#rubric">Rubric</a>
  </nav>

  <section id="lesson" class="content-section">
    <h2 class="section-heading">Lesson</h2>
    <div class="md">{readme_html}</div>
  </section>

  <section id="assignment" class="content-section">
    <h2 class="section-heading">Assignment</h2>
    <div class="md">{assignment_html}</div>
  </section>

  <section id="rubric" class="content-section">
    <h2 class="section-heading">Rubric</h2>
    <div class="md">{rubric_html}</div>
  </section>

  <div class="unit-footer-nav">
    {prev_link}
    {next_link}
  </div>
</main>"""
    return shell(f'{uid} — {title} | {meta["title"]}', "../../../style.css", body, home="../../../index.html")

# ---------------------------------------------------------------------------

def main():
    courses = []
    for slug in sorted(os.listdir(COURSES_DIR)):
        course_dir = os.path.join(COURSES_DIR, slug)
        if os.path.isdir(course_dir) and os.path.exists(os.path.join(course_dir, "meta.json")):
            meta, units = load_course(course_dir)
            courses.append({"slug": slug, "dir": course_dir, "meta": meta, "units": units})

    print(f"Found {len(courses)} course(s)")

    if os.path.isdir(DOCS_DIR):
        shutil.rmtree(DOCS_DIR)
    os.makedirs(DOCS_DIR)

    shutil.copy("style.css", os.path.join(DOCS_DIR, "style.css"))
    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()

    write(os.path.join(DOCS_DIR, "index.html"), build_root([{**c["meta"], "slug": c["slug"]} for c in courses]))
    print("  -> docs/index.html")

    for c in courses:
        meta, units = c["meta"], c["units"]
        write(os.path.join(DOCS_DIR, c["slug"], "index.html"), build_course_index(meta, units))
        print(f'  -> docs/{c["slug"]}/index.html ({len(units)} units)')
        for i, u in enumerate(units):
            prev_u = units[i - 1] if i > 0 else None
            next_u = units[i + 1] if i < len(units) - 1 else None
            out = os.path.join(DOCS_DIR, c["slug"], "units", u["folder"], "index.html")
            write(out, build_unit(meta, u, prev_u, next_u))
            print(f"  -> {out}")

    print("\nDone. Open docs/index.html in a browser.")

if __name__ == "__main__":
    main()
